inherit_gem:
  bixby: bixby_default.yml
AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
RSpec/ScatteredSetup:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'tasks/**/*'
    - 'db/schema.rb'
    - 'Rakefile'
    - '*.gemspec'
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true